name: CI
on: [push, pull_request]

env:
  SEQ_DB: sequelize_test
  SEQ_USER: sequelize_test
  SEQ_PW: sequelize_test

jobs:
  lint:
    name: Lint code and docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm install
      - run: npm run lint
      # - run: npm run lint-docs
  # test-typings:
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       ts-version: ['3.9', '4.0', '4.1']
  #   name: TS Typings (${{ matrix.ts-version }})
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: 12.x
  #     - run: npm install
  #     - run: npm install --save-dev typescript@~${{ matrix.ts-version }}
  #     - run: npm run test-typings
  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
      [
        lint,
        test-typings,
        test-sqlite,
        test-postgres,
        test-mysql-mariadb,
        test-mssql,
      ]
    if: github.event_name == 'push' # && github.ref == 'refs/heads/v6'
    env:
      GITHUBTOKEN: ${{ secrets.GITHUBTOKEN }}
      NPMTOKEN: ${{ secrets.NPMTOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm install
      - run: npm run semantic-release
